baseURL = "https://saugrin-sonia.fr/"
languageCode = "fr-fr"
title = "Developpeur FullStack PHP/JS  | ssaugrin"
uglyURLs = true

[params]
  author = "Sonia Saugrin"
  description = "Geek et développeur fullstack PHP/JS expérimenté vivant à l'île de La Réunion"
  images = ['screenshot.png']
  token = "123456"
  consumer_key = "13616-c877ca91826123ba561154b7"

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[build]
writeStats = true