baseURL = "https://saugrin-sonia.fr/"
languageCode = "fr-fr"
title = "Geek rêveur et développeur vivant dans son monde | ssaugrin"
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 20
defaultContentLanguage = 'fr'
rssLimit = 20
copyright = "2021 Janne Kemppainen All rights reserved"

[author]
	name = "Sonia SAUGRIN"
	email = "me@ssaugrin.fr"

[permalinks]
  posts = "/blog/:year/:title/"
  
[params]
  author = "Sonia Saugrin"
  images = ['screenshot.png']
  description = "Geek et développeur web expérimenté vivant à l'île de La Réunion"
  token = "123456"
  consumer_key = "13616-c877ca91826123ba561154b7"

[markup.goldmark.renderer]
unsafe= true

[build]
writeStats = true