[build]
  command = "npm run build"
  publish = "public"

[context.production]
  command = "npm install --include=optional && npm run build"

[[redirects]]
  from = "/2012/12/integrer-highcharts-a-du-php-csv"
  to = "/integrer-highcharts-a-du-php-csv"
  status = 301
  force = false

[[redirects]]
  from = "/2012/08/generer-des-graphiques-avec-highcharts-et-codeigniter"
  to = "/generer-des-graphiques-avec-highcharts-et-codeigniter"
  status = 301
  force = false

[[redirects]]
  from = "/2012/11/les-post-types-et-les-autres-fonctions-integrer-au-theme"
  to = "/"
  status = 301
  force = false
[build.environment]
  HUGO_VERSION = "0.152.2"
  NODE_VERSION = "20"
  NPM_VERSION = "11.4.2"
  NPM_FLAGS = "--include=optional"