url: https://saugrin-sonia.fr
name: Créatrice de solutions
description: 'J&#039;aime expérimenter, découvrir et apprendre au fur et à mesure de mes projets. Je ne reste pas en place, une personne m&#039;a qualifiée d&#039;électron libre. A vous d&#039;en juger !'
